pr:
  paths:
    include:
    - "src/CRMit.Customers/*"
    - "test/unittest/CRMit.Tests.Customers/*"


jobs:
  - job: unittest
    displayName: Unit Testing
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          projects: 'test/unittest/CRMit.Tests.Customers/CRMit.Tests.Customers.csproj'
