variables:
  - name: buildConfiguration
    value: Debug

  - name: projectName
    value: CRMit.Customers

  - name: coverageExclude
    value: "[*Tests]*,[*]*Startup,[*]*Program,[*]*DbContext,[*]*Models*"


jobs:
  - job: unittest
    displayName: Unit Testing
    steps:
      - task: UseDotNet@2
        inputs:
          version: '5.0.x'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          arguments: "--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/test/TestResults/Coverage/ /p:Exclude=\"$(coverageExclude)\""
          publishTestResults: true
          projects: 'test/unittest/$(projectName).UnitTests/$(projectName).UnitTests.csproj'

      - task: PublishCodeCoverageResults@1
        displayName: 'Publish code coverage report'
        inputs:
          codeCoverageTool: 'Cobertura'
          summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'
          