version: '3.4'

services:
  db-test:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=CustomersDB
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=customers_service
      - MYSQL_PASSWORD=password
