version: '3.4'

services:
  crmit-customers:
    image: ${DOCKER_REGISTRY-}crmit-customers
    build:
      context: .
      dockerfile: src/CRMit.Customers/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+
      - DB__SERVER=db
      - DB__PORT=3306
      - DB__DATABASE=CustomersDB
      - DB__USER=customers_service
      - DB__PASSWORD=password
    ports:
      - 8000:80
