version: '3.4'

services:
  crmit-customers:
    image: ${DOCKER_REGISTRY-}crmit-customers
    build:
      context: .
      dockerfile: src/CRMit.Customers/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+
      - CONNECTIONSTRINGS__CUSTOMERSDB=Server=db; Database=CustomersDB; User ID=sa; Password=Password1234;
    ports:
      - 8000:80
