version: '3.4'

services:
  crmit-customers:
    image: ${DOCKER_REGISTRY-}crmit-customers
    build:
      context: .
      dockerfile: src/CRMit.Customers/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+
      - ConnectionString=Server=db;Port=3306;Database=CustomersDB;Uid=customers_service;Pwd=password
    ports:
      - 8000:80
