version: '3.4'

services:
  crmit-customers:
    image: ${DOCKER_REGISTRY-}crmit-customers
    build:
      context: .
      dockerfile: src/CRMit.Customers/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+
      - CONNECTIONSTRINGS__CUSTOMERSDB=Server=db; Database=CustomersDB; User ID=sa; Password=Password1234;
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/crmit.customers.pfx
    volumes:
      - ${HOME}/.aspnet/https:/https/
    ports:
      - 8001:443
