version: '3.4'

services:
  crmit-customers:
    image: ${DOCKER_REGISTRY-}crmit-customers
    build:
      context: .
      dockerfile: src/CRMit.Customers/Dockerfile
    depends_on:
      - db
    networks:
      - crmit-customers
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 8080:80
