version: '3.4'

services:
  crmit-customers:
    image: ${DOCKER_REGISTRY-}crmit-customers
    build:
      context: .
      dockerfile: src/CRMit.Customers/Dockerfile
    ports:
      - 50080:80
      - 50443:443
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=CustomersDB
