name: Nuget

on:
  pull_request:
    branches:
      - master

jobs:
  nuget:
    name: Publish Nuget package
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: CRMit.Customers
      PROJECT_PATH: src/$PROJECT_NAME/$PROJECT_NAME.csproj

    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet CLI
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore
        run: dotnet restore $PROJECT_PATH

      - name: Build
        run: dotnet build --configuration Release --no-restore $PROJECT_PATH

      - name: Publish package
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: $PROJECT_PATH
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
