name: Release

on:
  pull_request:
    branches:
      - master

  push:
    tags:
      - v*

jobs:
  push_tag:
    name: Push tag to Docker repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Delete v1.0.0
        run: git tag -d v1.0.0