name: Release

on:
  pull_request:
    branches:
      - master
    tags:
      - v*

jobs:
  push_tag:
    name: Push tag to docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get last tag
        id: last_tag
        run: |
          tags=$(git tag -l)
          tag=${tags[0]}
          echo "::set-output name=tag::$tag"

      - name: Pull staging image
        run: docker pull dropik/crmit-customers:staging

      - name: Set tag
        run: docker tag dropik/crmit-customers:staging dropik/crmit-customers:${{ steps.last_tag.tag }}
      
      - name: Push tag
        run: docker push dropik/crmit-customers:${{ steps.last_tag.tag }}
